Vagrant.configure("2") do |config|
  # Define the box to use as the base image for the virtual machine
  config.vm.box = "bento/ubuntu-22.04"

  # Configure a bridged network interface with a static IP address
  config.vm.network "public_network",ip: "192.168.0.70", bridge: "Wi-Fi"
  config.vm.network "forwarded_port", guest: 8443, host: 8443
 
  # Configure the hardware resources for the virtual machine
  config.vm.provider "virtualbox" do |vb|
    vb.name = "servers"
    vb.memory = "10240"
    vb.cpus = 6
  end
  
  # Provisioning steps
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y gedit
  SHELL
end
