Vagrant.configure("2") do |config|
  # Master node configuration
  config.vm.define "k8s-master" do |master|
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.network "public_network", ip: "192.168.0.80", bridge: "Wi-Fi"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # 2 GB
      vb.cpus = 2       # 2 CPUs
      vb.name = "k8s-master"
    end

    # Provisioning for the master node (e.g., installing Kubernetes components)
    master.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y 
    SHELL
  end

  # Worker node 1 configuration
  config.vm.define "k8s-worker1" do |worker1|
    worker1.vm.box = "bento/ubuntu-22.04"
    worker1.vm.network "public_network", ip: "192.168.0.81", bridge: "Wi-Fi"
    worker1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # 2 GB
      vb.cpus = 2       # 2 CPUs
      vb.name = "k8s-worker1"
    end

    # Provisioning for worker node 1
    worker1.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get upgrade -y 
    SHELL
  end

  # Worker node 2 configuration
  config.vm.define "k8s-worker2" do |worker2|
    worker2.vm.box = "bento/ubuntu-22.04"
    worker2.vm.network "public_network", ip: "192.168.0.82", bridge: "Wi-Fi"
    worker2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # 2 GB
      vb.cpus = 2       # 2 CPUs
      vb.name = "k8s-worker2"
    end

    # Provisioning for worker node 2
    worker2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
    SHELL
  end
end
